FROM python:3.14.5-alpine
WORKDIR /service
RUN apk add --no-cache gcc musl-dev linux-headers python3-dev g++
COPY requirements.txt .
RUN pip install -r requirements.txt
ENV PYTHONPATH=/service
COPY . .
EXPOSE 8080
CMD ["python", "calculadora.py"]

